### ISSUE TITLE
Mustache peer dependency bump request

### ISSUE THREAD

**Issue by johndevedu** [jvitela/mustache-wax#6]
Thanks for your plugin! 

Quick question: we're getting a peer dependency warning in our application because we're using mustache v3 while your lib lists mustache ^0.8.1. Not very familiar with the mustache ecosystem -- how big is the difference between 0 to 3? If it's not too big, and it won't cause your lib to break, can you please bump to v3?

Thanks again!

**Comment by jvitela** [comment]
Hi @johndevedu 

I decided to remove the **peerDependencies** entry from package.json because starting with npm v3 these dependencies are no longer automatically installed and because this plugin is compatible with Mustache v0.8.1 and above (v4.0.1 being the latest right now), so it won't really make much sense to declare a specific version as peer dependency.

The change is published as v1.0.3. I hope this solves your problem.
